### ISSUE TITLE
Update snippets to conform to discord.py==2.1.0

### ISSUE THREAD

**Issue by cyrus01337** [wasi-master/vscode-discord.py-snippets#13]
I've noticed certain commonly used snippets like `!cog` will need to be updated so that the entry function and it's contents are async as per [the new changes](https://gist.github.com/Rapptz/6706e1c8f23ac27c98cee4dd985c8120), there may also be other discrepancies in other snippets.

What is the stance on this? I'm more than happy to go through the snippets that I know at the moment and prepare a PR if needed.

**Comment by wasi-master** [comment]
I haven't released/uploaded a version with your previous PR yet so you can update anything you want and create a new PR and I'll merge and release that instead

I have not used discord.py 2.1.0 yet so I don't know what needs to the changed :(
